name: .NET Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/publish_nightly_master.yml"
      - "DSharpPlus*/**"
      - "tools/**"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build_and_publish:
    name: Publish Nightly (Master)
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Package
        # If the package version does not comply with SemVer, it will be set as a pre-release version automatically.
        # We add 1195 since it's the last build number AppVeyor used.
        run: dotnet pack -o build -p:Nightly=$(printf \"%0*d\" 5 $(( 1195 + ${{ github.run_number }} )))
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DSharpPlus-Nightly-${{ github.run_number }}-${{ github.run_attempt }}.zip
          path: ./build/*
      - name: Publish nightly NuGet packages
        # Ensure we don't push nightlies to the nuget feed on PRs.
        if: github.event.pull_request == null
        run: |
          echo LATEST_STABLE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_ENV
          dotnet nuget push "build/*" --skip-duplicate -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
          dotnet run --project ./tools/AutoUpdateChannelDescription -p:VersionSuffix='nightly' -p:BuildNumber=$(printf \"%0*d\" 5 $(( 1195 + ${{ github.run_number }} )))
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_CHANNEL_TOPIC: ${{ secrets.DISCORD_CHANNEL_TOPIC }}
          NUGET_URL: ${{ secrets.NUGET_URL }}
          GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}
