name: "Test PR"
on:
  pull_request:

jobs:
  build_pr:
    runs-on: "self-hosted"
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "6.0.x"

      - name: "Build PR"
        run: "dotnet build --nologo"
      # TODO: Complete DSharpPlus.Test package. Utilizing Github secrets, we can run the bot and have it execute tests on the PR to ensure there aren't any breaking changes.
